//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joueurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Joueurs()
        {
            this.Match_joueur = new HashSet<Match_joueur>();
        }
    
        public int ID_Joueur { get; set; }
        public string NOM_Joueur { get; set; }
        public string PRENOM_Joueur { get; set; }
        public byte AGE_Joueur { get; set; }
        public byte NUMERO_Joueur { get; set; }
        public string POSTE_Joueur { get; set; }
        public int ID_Equipe { get; set; }
    
        public virtual Equipes Equipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match_joueur> Match_joueur { get; set; }
    }
}
