//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matchs()
        {
            this.Match_joueur = new HashSet<Match_joueur>();
            this.Equipes = new HashSet<Equipes>();
        }
    
        public int ID_Match { get; set; }
        public string LIEU_Match { get; set; }
        public System.DateTime DATE_Match { get; set; }
        public int ID_EQUIPE_VIS_Match { get; set; }
        public int ID_EQUIPE_DOM_Match { get; set; }
        public short SCORE_VIS_Match { get; set; }
        public short SCORE_DOM_Match { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match_joueur> Match_joueur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipes> Equipes { get; set; }
    }
}
